### PR TITLE
Bug fix: e2e tests didn't start

### PR DESCRIPTION
**Pull request by SviatlanaHlukhava**
Bug fix: e2e tests didn't start and not all tests were passed successfully

### CODE REVIEW

**Comment by UladzimirKapylou** [comment]
Does this successfully pass build in jenkins? I'll agree with it if so.

**Comment by UladzimirKapylou** [comment]
:+1:

**Comment by RomanKonovalov** [comment]
:+1:

**Comment by MikhailKavaleu** [comment]
:+1:

**Pull request merged**
