### PR TITLE
Feature/return documentation folder for swagger api page

### PR DESCRIPTION
**Pull request by MikhailKavaleu**
'documentation' folder with files for swagger's 'API-Docs REST' page has returned. Also this folder has removed from .gitignore
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by UladzimirKapylou** [comment]
Why do we need these files in our repo? Aren't they autogenerated?

**Comment by MikhailKavaleu** [comment]
Because they were deleted from project during transfer on git. And now addres http://evbymogsd0030.minsk.epam.com:7080/eighty/documentation/ is unavailable now. Project sources under mercurial contain these files.

**Comment by UladzimirKapylou** [comment]
Ok, did you write these files manually? I believe, not. So, how they appear there? **What** created them? What I should do to recreate them again?

**Comment by MikhailKavaleu** [comment]
All these files are a swagger ui part (https://github.com/swagger-api/swagger-ui) . Which is using as-is, just cloned from github and copied to webapp folder for using it as part of the project.
These files is a non dependency collection of HTML, Javascript, and CSS and must be permanently attached to the project

**Comment by UladzimirKapylou** [comment]
Let's investigate this some more time. I think, there is a way to download these files automatically.

**Comment by UladzimirKapylou** [comment]
Much better. Thanks :+1:

**Comment by RomanKonovalov** [comment]
:+1:

**Comment by SviatlanaHlukhava** [comment]
:+1:

**Pull request merged**
