### PR TITLE
Add grunt clean task to maven

### PR DESCRIPTION
**Pull request by RomanKonovalov**
Add grunt clean task to maven

### CODE REVIEW

**Comment by UladzimirKapylou** [comment]
Why do we need this step?

**Comment by RomanKonovalov** [comment]
This task deletes autogenerated files from previous build

**Comment by UladzimirKapylou** [comment]
Will they not be overwritten with new files?

**Comment by RomanKonovalov** [comment]
Karma tries to test minified file from the previuos build and fails. So I think we shouldn't have any autogenerated files before tests

**Comment by UladzimirKapylou** [comment]
:+1:

**Comment by SviatlanaHlukhava** [comment]
:+1:

**Pull request merged**
