### PR TITLE
Add code quality

### PR DESCRIPTION
**Pull request by RomanKonovalov**
Add checkstyle, findbugs, pmd. Add maven build scripts.

### CODE REVIEW

**Comment by SviatlanaHlukhava** [comment]
:+1:

**Comment by UladzimirKapylou** [comment]
Why have you added jacoco? As I remember, we were using cobertura in 80 early.

**Comment by MikhailKavaleu** [comment]
:+1:

**Comment by UladzimirKapylou** [comment]
Ok. But, guys do not follow these rules blindly. They are abstract. If you think that some rule is not applicable for us, then let's discuss it.

**Comment by UladzimirKapylou** [comment]
Also, I know that we have modified rules set for checkstyle in our sonar. Did you compare your xml with that? I think, it would be better to do it before commit.

**Comment by UladzimirKapylou** [comment]
:+1:

**Pull request merged**
